pilot:
  autoscaleEnabled: false
  traceSampling: 100
  configMap: true
meshConfig:
  enablePrometheusMerge: true
  defaultConfig:
    holdApplicationUntilProxyStarts: true
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    proxyStatsMatcher:
      inclusionPrefixes:
        - cluster.outbound
        - listener.
        - cluster.xds-grpc