apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio
  namespace: istio-system
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      istio: prometheus
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: http-envoy-prom
      interval: 15s