fullnameOverride: prometheus

grafana:
  enabled: true
  adminPassword: prom-operator
  service:
    type: ClusterIP
  persistence:
    enabled: false
  defaultDashboardsEnabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    ruleSelector: {}
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

additionalServiceMonitors:
  - name: istiod
    selector:
      matchLabels:
        app: istiod
    namespaceSelector:
      matchNames:
        - istio-system
    endpoints:
      - port: http-monitoring
        interval: 15s

  - name: istio-ingressgateway
    selector:
      matchLabels:
        app: istio-ingressgateway
    namespaceSelector:
      matchNames:
        - istio-system
    endpoints:
      - port: http-monitoring
        interval: 15s

  - name: istio-telemetry
    selector:
      matchLabels:
        app: istio-telemetry
    namespaceSelector:
      matchNames:
        - istio-system
    endpoints:
      - port: http-monitoring
        interval: 15s