apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.12.1
    helm:
      values: |
        config:
          registries:
            - name: ghcr
              prefix: ghcr.io
              credentials:
                username: $GITHUB_USER
                password: $GITHUB_TOKEN
              default: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true