apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.12.1
    helm:
      values: |
        fullnameOverride: argocd-image-updater
        config:
          argocd:
            grpcWeb: true
            serverAddress: "argocd-server.argocd.svc"
            insecure: true
          logLevel: info
        rbac:
          create: true
        serviceAccount:
          create: true
          name: argocd-image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true