apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.12.1
    helm:
      values: |
        config:
          registries:
            - name: GitHub Container Registry
              prefix: ghcr.io
              credentials:
                username: '{{ github.username }}'
                password: '{{ github.token }}'
          argocd:
            serverAddr: "argocd-server.argocd.svc:443"
            grpcWeb: true
            insecure: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true