apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-guestbook
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: flask-guestbook=ghcr.io/eharriett0/flask-guestbook
spec:
  project: default
  source:
    repoURL: https://github.com/eharriett0/app-deployments
    targetRevision: HEAD
    path: flask-guestbook
    helm:
      valueFiles:
        - values.yaml
      values: |
        podAnnotations:
          reloader.stakater.com/auto: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true