# infra-gitops/values/argocd-values.yaml

server:
  service:
    type: NodePort
  ingress:
    enabled: false

configs:
  registries:
    enabled: true
    secret:
      name: argocd-image-updater-secret
      key: registries.conf
  params:
    server.insecure: true

# Optional: disable Argo CD notifications if you're not using them yet
notifications:
  enabled: false

annotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous

controller:
  parallelism:
    limit: 20  # default is 10
