apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: backstage
    targetRevision: 20.1.3
    helm:
      releaseName: backstage
      values: |
        service:
          type: ClusterIP

        appConfig:
          catalog:
            locations:
              - type: url
                target: https://raw.githubusercontent.com/eharriett0/app-deployments/main/flask-guestbook/catalog-info.yaml
              - type: url
                target: https://raw.githubusercontent.com/eharriett0/app-deployments/main/sentiment-service/catalog-info.yaml

        ingress:
          enabled: false # using Istio instead

  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true