apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: 1.5.1
    helm:
      releaseName: backstage
      values: |
        service:
          type: ClusterIP

        appConfig:
          app:
            title: Minikube Platform
          backend:
            baseUrl: http://backstage.platform.local # we’ll route this via Istio later
          frontend:
            baseUrl: http://backstage.platform.local

        ingress:
          enabled: false # using Istio instead

  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true