apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-fluentbit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: fluent-bit
    targetRevision: 2.3.0
    helm:
      releaseName: fluentbit
      valueFiles:
        - ../values/fluentbit.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true