apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-cleanup
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eharriett0/infra-gitops.git
    targetRevision: main
    path: argo/infra/kube-cleanup/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true