apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: Opaque
stringData:
  registries.conf: |
    registries:
      - name: ghcr
        prefix: ghcr.io
        credentials:
          username: $GITHUB_USER
          password: $GITHUB_TOKEN
        default: true