apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  sources:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.5.1
      helm:
        values: |
          replicas: 1
          minimumMasterNodes: 1
          tls:
            enabled: false
    - repoURL: https://helm.elastic.co
      chart: kibana
      targetRevision: 8.5.1
      helm:
        values: |
          service:
            type: NodePort
          elasticsearchHosts: "http://elasticsearch-master.elk.svc.cluster.local:9200"
          elasticsearchSSL: false
          elasticsearchCertificateAuthorities: []
          security:
            enabled: false
    - repoURL: https://charts.bitnami.com/bitnami
      chart: fluent-bit
      targetRevision: 2.3.0
      helm:
        values: |
          backend:
            type: es
            es:
              host: elasticsearch-master.elk.svc.cluster.local
              port: 9200
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true