apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: elasticsearch
      targetRevision: 19.7.1
      helm:
        valueFiles:
          - elasticsearch-values.yaml
    - repoURL: https://helm.elastic.co
      chart: kibana
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - kibana-values.yaml
    - repoURL: https://charts.bitnami.com/bitnami
      chart: fluent-bit
      targetRevision: 2.3.0
      helm:
        valueFiles:
          - fluent-bit-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true