apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eharriett0/infra-gitops.git
    targetRevision: main
    path: argo/infra/monitoring/elk
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true