apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  sources:
    - repoURL: https://github.com/eharriett0/infra-gitops
      targetRevision: main
      path: argo/infra/monitoring/elk/secrets
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.5.1
      helm:
        values: |
          replicas: 1
          minimumMasterNodes: 1
          tls:
            selfSignedCertificate:
              enabled: false
          volumeMounts:
            - name: certs
              mountPath: /usr/share/elasticsearch/config/certs
              readOnly: true
          extraVolumes:
            - name: certs
              secret:
                secretName: elasticsearch-master-certs
    - repoURL: https://helm.elastic.co
      chart: kibana
      targetRevision: 8.5.1
      helm:
        values: |
          service:
            type: NodePort
          elasticsearchHosts: "https://elasticsearch-master.elk.svc.cluster.local:9200"
          elasticsearchSSL: true
          elasticsearchCertificateAuthorities:
            - /usr/share/kibana/config/certs/ca.crt
          extraVolumes:
            - name: elasticsearch-certs
              secret:
                secretName: elasticsearch-master-certs
          extraVolumeMounts:
            - name: elasticsearch-certs
              mountPath: /usr/share/kibana/config/certs
              readOnly: true
    - repoURL: https://charts.bitnami.com/bitnami
      chart: fluent-bit
      targetRevision: 2.3.0
      helm:
        values: |
          backend:
            type: es
            es:
              host: https://elasticsearch-master.elk.svc.cluster.local
              port: 9200
              tls: true
              tls.verify: false  # Optional if using self-signed cert
              tls.ca_file: /fluent-bit/tls/ca.crt
          extraVolumeMounts:
            - name: elasticsearch-certs
              mountPath: /fluent-bit/tls
              readOnly: true
          extraVolumes:
            - name: elasticsearch-certs
              secret:
                secretName: elasticsearch-master-certs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true