apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elk-pod-access
  namespace: elk
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elk-pod-access-binding
  namespace: elk
subjects:
  - kind: ServiceAccount
    name: default
    namespace: elk
roleRef:
  kind: Role
  name: elk-pod-access
  apiGroup: rbac.authorization.k8s.io