apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-fluentbit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: fluent-bit
    targetRevision: 2.3.0
    helm:
      values: |
        backend:
          type: es
          es:
            host: https://elasticsearch-master.elk.svc.cluster.local
            port: 9200
            tls: true
            tls.verify: false  # Optional for self-signed certs
            tls.ca_file: /fluent-bit/tls/ca.crt
        extraVolumeMounts:
          - name: elasticsearch-certs
            mountPath: /fluent-bit/tls
            readOnly: true
        extraVolumes:
          - name: elasticsearch-certs
            secret:
              secretName: elasticsearch-master-certs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true