apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-master-certs
  namespace: elk
spec:
  secretName: elasticsearch-master-certs
  duration: 8760h # 1y
  renewBefore: 360h # 15d
  subject:
    organizations:
      - elk-stack
  dnsNames:
    - elasticsearch-master
    - elasticsearch-master.elk
    - elasticsearch-master.elk.svc
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer