apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-credentials
  namespace: elk
type: Opaque
stringData:
  username: elastic
  password: test  # or use a real password you plan to rotate later